apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: gittools
  name: gittools
spec:
  containers:
  - image: docker.io/sandervanvugt/gittools
    name: gittools
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
