apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: oldbird
    type: allbirds
  name: oldbird
  namespace: birds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oldbird
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: oldbird
        type: allbirds
    spec:
      containers:
      - image: nginx:1.17
        name: nginx
        resources: {}
status: {}
