apiVersion: v1
kind: Pod
metadata:
  name: sidepod
spec:
      containers:
        - name: myapp
          image: nginx:latest
      initContainers:
        - name: logshipper
          image: alpine:latest
          restartPolicy: Always
          command: ['sleep','15'] 
