apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: securepod
  name: securepod
spec:
  containers:
  - image: nginx
    name: securedpod
    resources: {}
    securityContext: 
      allowPrivilegeEscalation: false
      runAsGroup: 2000
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  securityContext:
    fsGroup: 2000
status: {}
