apiVersion: v1
kind: Pod
metadata:
  name: oregonpod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
      - name: config-volume
        mountPath: /usr/share/nginx/html
  volumes:
    - name: config-volume
      configMap:
        name: task3cm
