apiVersion: v1
kind: Pod
metadata:
  name: probepod
  namespace: probes
spec:
  containers:
  - name: main
    image: busybox
    command:
      - sleep 
      -  '3600'
    livenessProbe:
      exec:
        command:
          - wget
          - --no-check-certificate
          - --spider
          - https://192.168.39.103:8443/healthz
      initialDelaySeconds: 3
      periodSeconds: 3

