apiVersion: v1
kind: Pod
metadata:
  name: storepod
spec:
  containers:
  - name: example-container
    image: nginx:latest
    volumeMounts:
    - mountPath: /usr/share/nginx/index.html
      name: example-volume
  volumes:
  - name: example-volume
    hostPath:
      path: /webapp
